name: Lint Scripts

on:
  push:
    branches: [main, develop]
    paths:
      - '**/*.sh'
      - '**/*.lua'
      - '.github/workflows/lint-scripts.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - '**/*.sh'
      - '**/*.lua'
      - '.github/workflows/lint-scripts.yml'
  workflow_dispatch:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      
      - name: List shell scripts
        id: find_scripts
        run: |
          if [[ -d "./scripts" && $(find ./scripts -name "*.sh" | wc -l) -gt 0 ]]; then
            echo "SHELL_SCRIPTS_EXIST=true" >> $GITHUB_ENV
            find ./scripts -name "*.sh" -type f
          else
            echo "SHELL_SCRIPTS_EXIST=false" >> $GITHUB_ENV
            echo "No shell scripts found in ./scripts directory"
          fi
      
      - name: Run shellcheck with relaxed settings
        if: env.SHELL_SCRIPTS_EXIST == 'true'
        run: |
          echo "Running shellcheck on shell scripts with relaxed settings:"
          # Skip some warnings that are difficult to fix in older scripts
          # SC2034: Variable appears unused
          # SC2155: Declare and assign separately
          # SC2164: Use cd ... || exit in case cd fails
          # SC2124: Assigning array to string will make it coalesce
          # SC2064: Use single quotes for trap
          # SC2086: Double quote to prevent globbing and word splitting
          # SC2001: See if you can use ${variable//search/replace} instead
          # SC2046: Quote this to prevent word splitting
          # SC2206: Quote to prevent word splitting/globbing
          find ./scripts -name "*.sh" -type f -print0 | \
            xargs -0 shellcheck --exclude=SC2034,SC2155,SC2164,SC2124,SC2064,SC2086,SC2001,SC2046,SC2206 --severity=error

  luacheck:
    name: Lua Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check for Lua files
        id: check-lua
        run: |
          if [[ $(find . -name "*.lua" | wc -l) -gt 0 ]]; then
            echo "LUA_FILES_EXIST=true" >> $GITHUB_ENV
            echo "Found Lua files:"
            find . -name "*.lua" -type f | head -5
          else
            echo "LUA_FILES_EXIST=false" >> $GITHUB_ENV
            echo "No Lua files found in repository"
          fi
      
      - name: Set up Lua
        if: env.LUA_FILES_EXIST == 'true'
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"
      
      - name: Set up LuaRocks
        if: env.LUA_FILES_EXIST == 'true'
        uses: leafo/gh-actions-luarocks@v4
      
      - name: Install luacheck
        if: env.LUA_FILES_EXIST == 'true'
        run: luarocks install luacheck
      
      - name: Run luacheck with relaxed settings
        if: env.LUA_FILES_EXIST == 'true'
        run: |
          echo "Creating .luacheckrc with relaxed settings"
          cat > .luacheckrc << 'EOF'
          max_line_length = false
          std = {
            globals = {"vim", "assert", "describe", "it", "before_each", "after_each"}
          }
          exclude_files = {
            "deps/**",
            ".luarocks/**"
          }
          ignore = {
            "212", -- Unused argument
            "213", -- Unused loop variable
            "421", -- Shadowing a local variable
            "431", -- Shadowing an upvalue
            "631", -- Line is too long
            "611", -- A line contains trailing whitespace
            "614", -- Trailing whitespace
            "581", -- Negation operator can be replaced
          }
          EOF
          
          echo "Running luacheck with relaxed settings:"
          luacheck . --config .luacheckrc