name: Lint Scripts

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.sh'
      - '.github/workflows/lint-scripts.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.sh'
      - '.github/workflows/lint-scripts.yml'
  workflow_dispatch:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      
      - name: List shell scripts
        id: find_scripts
        run: |
          if [[ -d "./scripts" && $(find ./scripts -name "*.sh" | wc -l) -gt 0 ]]; then
            echo "SHELL_SCRIPTS_EXIST=true" >> $GITHUB_ENV
            find ./scripts -name "*.sh" -type f
          else
            echo "SHELL_SCRIPTS_EXIST=false" >> $GITHUB_ENV
            echo "No shell scripts found in ./scripts directory"
          fi
      
      - name: Run shellcheck with relaxed settings
        if: env.SHELL_SCRIPTS_EXIST == 'true'
        run: |
          echo "Running shellcheck on shell scripts with relaxed settings:"
          # Skip some warnings that are difficult to fix in older scripts
          # SC2034: Variable appears unused
          # SC2155: Declare and assign separately
          # SC2164: Use cd ... || exit in case cd fails
          # SC2124: Assigning array to string will make it coalesce
          # SC2064: Use single quotes for trap
          find ./scripts -name "*.sh" -type f -print0 | \
            xargs -0 shellcheck --exclude=SC2034,SC2155,SC2164,SC2124,SC2064 --severity=error